parameters:
  serviceConnection: "DCD-CFTAPPS-DEV"
  aksResourceGroup: "preview-01-rg"
  aksCluster: "preview-01-aks"
  acrName: "hmcts"
  chartName: ""
  chartReleaseName: ""
  chartNamespace: ""
  helmVersion: "3.2.4"

jobs:
  - job: ValidateChart
    pool:
      vmImage: "Ubuntu 16.04"
    steps:
      - template: ../../steps/charts/release.yaml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
          aksResourceGroup: ${{ parameters.aksResourceGroup }}
          aksCluster: ${{ parameters.aksCluster }}
          acrName: ${{ parameters.acrName }}
          chartName: ${{ parameters.chartName }}
          chartReleaseName: ${{ parameters.chartReleaseName }}
          chartNamespace: ${{ parameters.chartNamespace }}
          helmVersion: ${{ parameters.helmVersion }}
