parameters:
  serviceConnection: "azurerm-nonprod"
  aksResourceGroup: "cnp-aks-rg"
  aksCluster: "cnp-aks-cluster"
  chartName: ""
  chartReleaseName: ""
  chartNamespace: ""
  helmVersion: "3.0.2"

jobs:
  - job: ValidateChart
    pool:
      vmImage: "Ubuntu 16.04"
    steps:
      - template: ../../steps/charts/validate.yaml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
          aksResourceGroup: ${{ parameters.aksResourceGroup }}
          aksCluster: ${{ parameters.aksCluster }}
          chartName: ${{ parameters.chartName }}
          chartReleaseName: ${{ parameters.chartReleaseName }}
          chartNamespace: ${{ parameters.chartNamespace }}
          helmVersion: ${{ parameters.helmVersion }}
