parameters:
  serviceConnection: ''

steps:
- task: AzureCLI@2
  displayName: 'Configure Helm with ACR'
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    scriptLocation: 'inlineScript'
    scriptType: 'bash'
    inlineScript: |
      ACR_NAME=hmctssandbox
      az acr login --name $ACR_NAME
      helm repo add $ACR_NAME https://$ACR_NAME.azurecr.io/helm/v1/repo