parameters:
  serviceConnection: ''

steps:
- task: AzureCLI@1
  displayName: 'Configure Helm with ACR'
  enabled: true
  inputs:
    azureSubscription:  ${{ parameters.serviceConnection }}
    scriptLocation: 'inlineScript'
    inlineScript: |
      ACR_NAME=hmctssandbox
      az configure --defaults acr=hmctssandbox
      helm repo add $ACR_NAME https://$ACR_NAME.azurecr.io/helm/v1/repo
