parameters:
  serviceConnection: ''

jobs:
- job: JavaBuild
  dependsOn: LaunchAgent
  pool:
    name: 'mgmt-aks-sandbox'
    demands:
    - agent.name -equals $(projectName)-$(Build.BuildId)

  steps:
  - script: 'env'
    displayName: 'Display Environment Variables'

  - task: AzureKeyVault@2
    displayName: 'Get secrets from Keyvault'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      keyVaultName: 'infra-vault-sandbox'
      secretsFilter: 'sonarcloud-api-token,OWASPDb-Account,OWASPDb-Password'

  - template: ../tasks/gradle.yaml
    parameters:
      displayName: 'Gradle Assemble'
      tasks: 'assemble'
      options: '-Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$(sonarcloud-api-token) -Dsonar.organization=hmcts'

  - template: ../tasks/sonarcloud-build-breaker.yaml

  - template: ../tasks/owasp-security-check.yaml

  - template: ../steps/acr-build.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}

  - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    - template: ../steps/aks-deploy.yaml
      parameters:
        serviceConnection: ${{ parameters.serviceConnection }}