parameters:
  registryServiceConnection: "azurerm-prod"
  acrName: "hmctsprod"

steps:
  - task: AzureCLI@2
    displayName: "ACR Login for Helm"
    inputs:
      azureSubscription: ${{ parameters.registryServiceConnection }}
      scriptLocation: "inlineScript"
      scriptType: bash
      inlineScript: |
        export HELM_EXPERIMENTAL_OCI=1
        az acr login --name ${{ parameters.acrName }}

